name: "medallion_air_quality"
version: "1.0.0"
config-version: 2

profile: "medallion_air_quality"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  medallion_air_quality:
    gold:
      +materialized: external
